name: Check ESLint errors

on:
  push:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanoeb/eslint-action@1.0.2
      - name: Installation
      - run: yarn
      - name: Lint
      - run: yarn lint:ci
      
  
