name: Check ESLint errors

on:
  push:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - with: 
              cache: yarn
      - name: Installation
      - run: yarn
      - name: Lint
      - run: yarn lint:ci
      
  
