name: tsc errors check

on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14 # I used node v14, but you this could be any version less
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: yarn install
      run: yarn install
    - name: tsc
      uses: icrawl/action-tsc@v1